### ISSUE TITLE
since 0.8 on Windows  QGIS 3.32

### ISSUE THREAD

**Issue by Amphibitus** [lmotta/debug_vs_plugin#13]
2023-08-16T09:11:49     WARNING    Traceback (most recent call last):
              File "C:\Users/Gerd/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\debug_vs\__init__.py", line 131, in enable
              if self.debugpy.is_client_connected():
              File "C:\Users\Gerd\AppData\Roaming\Python\Python39\site-packages\debugpy\public_api.py", line 28, in wrapper
              from debugpy.server import api
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users\Gerd\AppData\Roaming\Python\Python39\site-packages\debugpy\server\api.py", line 16, in 
              from pydevd_file_utils import absolute_path
             ImportError: cannot import name 'absolute_path' from 'pydevd_file_utils' (C:\OSGeo4W\apps\Python39\lib\site-packages\ptvsd\_vendored\pydevd\pydevd_file_utils.py)

**Comment by byander** [comment]
I had the same problem on Windows 10.
My solution to jump the error was a downgrade version to the 0.7: 
* Uninstall the plugin debugpy;
* Install the package ptvsd (depreciate);
* Download version 0.7 from official repository: https://plugins.qgis.org/plugins/debug_vs/
* Install the plugin from zip file.

Isn't a good solution, I know that, but it works until someone discovers to fix this.

**Comment by deltamarnix** [comment]
I'm still stuck on 0.7 as a workaround. Are there any updates planned in the coming time?
