### ISSUE TITLE
 RuntimeError: timed out waiting for adapter to connect

### ISSUE THREAD

**Issue by axeis** [lmotta/debug_vs_plugin#17]
When "Enable Debug for VS Code" I immediately get this in the Python-Output:
```
2024-04-18T16:37:37     WARNING    Traceback (most recent call last):
              File "C:\Users\Max\AppData\Roaming\Python\Python39\site-packages\debugpy\server\api.py", line 237, in listen
              sock, _ = endpoints_listener.accept()
              File "C:\PROGRA~1\QGIS\apps\Python39\lib\socket.py", line 293, in accept
              fd, addr = self._accept()
             socket.timeout: timed out
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\Users/Max/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\debug_vs\__init__.py", line 134, in enable
              t_, self.port = self.debugpy.listen((self.host, self.port))
              File "C:\Users\Max\AppData\Roaming\Python\Python39\site-packages\debugpy\public_api.py", line 31, in wrapper
              return wrapped(*args, **kwargs)
              File "C:\Users\Max\AppData\Roaming\Python\Python39\site-packages\debugpy\server\api.py", line 143, in debug
              log.reraise_exception("{0}() failed:", func.__name__, level="info")
              File "C:\Users\Max\AppData\Roaming\Python\Python39\site-packages\debugpy\server\api.py", line 141, in debug
              return func(address, settrace_kwargs, **kwargs)
              File "C:\Users\Max\AppData\Roaming\Python\Python39\site-packages\debugpy\server\api.py", line 251, in listen
              raise RuntimeError("timed out waiting for adapter to connect")
             RuntimeError: timed out waiting for adapter to connect
```

Also another QGIS Instance opens. Is that intended? 
The second instance has these warnings:

```
2024-04-18T16:37:35     CRITICAL    Ungültige Datenquelle : C:\Users\Max\AppData\Roaming\Python\Python39\site-packages\debugpy\adapter ist keine gültige oder erkannte Datenquelle.
2024-04-18T16:37:35     CRITICAL    Ungültige Datenquelle : C:\Users\Max\Documents\--for-server ist keine gültige oder erkannte Datenquelle.
2024-04-18T16:37:35     CRITICAL    Ungültige Datenquelle : C:\Users\Max\Documents\51955 ist keine gültige oder erkannte Datenquelle.
2024-04-18T16:37:35     CRITICAL    Ungültige Datenquelle : C:\Users\Max\Documents\--host ist keine gültige oder erkannte Datenquelle.
2024-04-18T16:37:35     CRITICAL    Ungültige Datenquelle : C:\Users\Max\Documents\localhost ist keine gültige oder erkannte Datenquelle.
2024-04-18T16:37:35     CRITICAL    Ungültige Datenquelle : C:\Users\Max\Documents\--port ist keine gültige oder erkannte Datenquelle.
2024-04-18T16:37:35     CRITICAL    Ungültige Datenquelle : C:\Users\Max\Documents\5678 ist keine gültige oder erkannte Datenquelle.
2024-04-18T16:37:35     CRITICAL    Ungültige Datenquelle : C:\Users\Max\Documents\--server-access-token ist keine gültige oder erkannte Datenquelle.
2024-04-18T16:37:35     CRITICAL    Ungültige Datenquelle : C:\Users\Max\Documents\87b14caf40d0de120e50a9716da53c0ef13136314dba2001e8038a4cff3ed0d2 ist keine gültige oder erkannte Datenquelle.
```

I am using QGIS 3.34.5 on Windows 10. 
Debugpy was installed in the QGIS python env by default.

**Comment by mlechner** [comment]
Same here on QGIS 3.34.11 on Win10. debugpy has been installed using "python -m pip install debugpy" from QGIS Installdir. "import debugpy" ist successful from QGIS internal python console.
Anyone who solved the problem already?

**Comment by Crispin-at-Linknode** [comment]
I solved this with 2 actions... but not sure if I only required the second

1. the install from pip install debugpy installs 1.8.1 but 1.8.xx is available from debugpy so I used that

2. A similar issue is reported on https://github.com/microsoft/debugpy/issues/456 and so the solution is to add the following line to your plugins\debug_vs\__init__.py (at around line 134 just before the listener call)>>
3. 
        self.debugpy.configure(python=r"C:\OSGeo4W\apps\Python312\python.exe")

**Comment by pers-ephone** [comment]
> I solved this with 2 actions... but not sure if I only required the second
> 
>     1. the install from pip install debugpy installs 1.8.1 but 1.8.xx is available from debugpy so I used that
> 
>     2. A similar issue is reported on [listen throws "RuntimeError: timed out waiting for adapter to connect" microsoft/debugpy#456](https://github.com/microsoft/debugpy/issues/456) and so the solution is to add the following line to your plugins\debug_vs__init__.py (at around line 134 just before the listener call)>>
> 
>     3. ```
>         self.debugpy.configure(python=r"C:\OSGeo4W\apps\Python312\python.exe")
>        ```

This issue is solved by adding this line, maybe in a more generalized way, in the pull request https://github.com/lmotta/debug_vs_plugin/pull/18 by sanak. Problem is this repo seems abandoned. To anyone searching for a solution use the fork of @sanak used to PR.
