### ISSUE TITLE
First load error

### ISSUE THREAD

**Issue by Gaetanbrl** [lmotta/debug_vs_plugin#4]
Hi,

I try to use this awesome plugin but Qgis can't load it : 

```
SyntaxError: invalid syntax 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 309, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/pierre/.local/share/QGIS/QGIS3/profiles/default/python/plugins/debug_vs/__init__.py", line 64
    self.iface.addPluginToMenu( f"&{self.nameAction}" , self.action)
                                                    ^
SyntaxError: invalid syntax


Version de Python : 3.5.3 (default, Jul  9 2020, 13:00:10) [GCC 6.3.0 20170516] 
Version de QGIS : 3.4.12-Madeira Madeira, 625767347a 
```

Have i a version issue ? How to fix it ?

Thanks.

**Comment by lmotta** [comment]
Most users have used this plugin.

You  can reinstall the plugin.

PS: I use the QGIS 3.10 (LTS)

**Comment by Gaetanbrl** [comment]
> Most users have used this plugin.

Thanks for this details...
